# Generated by Django 6.0.2 on 2026-03-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('DIS', 'Disponible'), ('OCU', 'En uso'), ('MAN', 'En mantenimiento')], default='DIS', max_length=3)),
                ('descripcion', models.TextField()),
                ('placas', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('hora_regreso', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('COM', 'Completada'), ('CAN', 'Cancelada')], default='ACT', max_length=3)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='FotoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos_fotos/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Fotomulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'En proceso'), ('PAG', 'Pagada')], max_length=3)),
                ('ubicacion', models.CharField(max_length=200)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificacion', models.DateField()),
                ('tenencia', models.CharField(max_length=20)),
                ('control', models.DateField()),
                ('seguro_vigencia', models.DateField()),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.vehiculo')),
            ],
        ),
    ]
